version: '3'

services:

  # ajax version
  # tornappajax:
  #   build: ./appajax/
  #   command: python3 ./chatdemo.py
  #   volumes:
  #     - ./app:/app
  #     - ./logs:/tmp/flask
  #   ports:
  #    - 8888:8888
  #   depends_on:
  #    - db
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "20m"
  #       max-file: "10"

  # socket version
  tornappsocket:
    build: ./appsocket/
    command: python3 ./chatdemo.py
    volumes:
      - ./app:/app
      - ./logs:/tmp/flask
    ports:
     - 8888:8888
    depends_on:
     - db
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwpassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
