version: '3'

services:

  tornapp:
    build: ./app/
    # command: python3 /home/tornado/chat/chatdemo
    command: python3 ./chat/chatdemo.py > /var/log/tornado/flask.log
    # command: ls
    volumes:
      - ./app:/app
      - ./logs:/tmp/flask
    ports:
     - 8888:8888
    depends_on:
     - db
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwpassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
