version: '3'

services:

  tornapp:
    build: ./app/
    # command: python3 /home/tornado/chat/chatdemo
    command: python3 ./chat/chatdemo.py
    # command: ls
    volumes:
      - ./app:/app
    ports:
     - 8888:8888
    depends_on:
     - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwpassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./tmp:/tmp
    ports:
      - 5432:5432
